# 1. Conexión Directa a la Base de Datos (Se queda igual)
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/appweb_miguelrojas
spring.datasource.username=root
spring.datasource.password=Admin123*

# 2. Configuración JPA e Hibernate (Corregido con una opción válida del enum)
spring.jpa.database=MYSQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB

# 3. Tu Secreto JWT
jwt.secret=aEIu9S7cvZUnPJWezau3rKUCxj4BLtpCVzhVSyam93prJOxofs7688P0OD5tmTIsLL6u7G9HpXvT
