SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE user_role;
TRUNCATE TABLE menu_role;
TRUNCATE TABLE notificacion;
TRUNCATE TABLE documentos_legales;
TRUNCATE TABLE audiencia;
TRUNCATE TABLE pago;
TRUNCATE TABLE cita;
TRUNCATE TABLE expediente;
TRUNCATE TABLE caso;
TRUNCATE TABLE abogado_servicio;
TRUNCATE TABLE abogado_area;
TRUNCATE TABLE servicio_legal;
TRUNCATE TABLE area_derecho;
TRUNCATE TABLE cliente;
TRUNCATE TABLE abogado;
TRUNCATE TABLE especialista;
TRUNCATE TABLE menu;
TRUNCATE TABLE rol;
TRUNCATE TABLE usuarios;

SET FOREIGN_KEY_CHECKS = 1;
